//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class TruckDriver
    {
        public int id { get; set; }
        public int truckId { get; set; }
        public int driverId { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }

        [JsonIgnore]
        public virtual Driver Driver { get; set; }
        [JsonIgnore]
        public virtual Truck Truck { get; set; }
    }
}
